/*INSERT PARA FILIAL TEMPORÁRIO*/
INSERT INTO LIVRARIA.FILIAL(NOME_FILIAL, CIDADE)
VALUES ('Matriz', 'São Paulo');
INSERT INTO LIVRARIA.FILIAL(NOME_FILIAL, CIDADE)
VALUES ('Brasilia','Brasilia');
INSERT INTO LIVRARIA.FILIAL(NOME_FILIAL, CIDADE)
VALUES ('Campina Grande','Campina Grande');
INSERT INTO LIVRARIA.FILIAL(NOME_FILIAL, CIDADE)
VALUES ('Joinville','Joinville');

/*INSERT PARA DEPARTAMENTO PARA FILIAL MATRIZ - 1*/
INSERT INTO LIVRARIA.DEPARTAMENTO(NOME_DPT, FK_ID_FILIAL)
VALUES('DIRETORIA','1');
INSERT INTO LIVRARIA.DEPARTAMENTO(NOME_DPT, FK_ID_FILIAL)
VALUES('PRODUTOS/MARKETING','1');
INSERT INTO LIVRARIA.DEPARTAMENTO(NOME_DPT, FK_ID_FILIAL)
VALUES('TI','1');
INSERT INTO LIVRARIA.DEPARTAMENTO(NOME_DPT, FK_ID_FILIAL)
VALUES('VENDAS','1');