CREATE DATABASE LIVRARIA;
USE LIVRARIA;

CREATE TABLE CLIENTE (
    ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(50) UNIQUE NOT NULL,
    DATA_NASC Varchar(89),
    SEXO VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(14) NOT NULL,
    PRIMARY KEY(ID_CLIENTE)
);

CREATE TABLE FILIAL(
  ID_FILIAL INT NOT NULL AUTO_INCREMENT,
  NOME_FILIAL VARCHAR(20) NOT NULL,
  CIDADE VARCHAR(25) NOT NULL,
  PRIMARY KEY(ID_FILIAL)
);

CREATE TABLE DEPARTAMENTO(
  ID_DPT INT NOT NULL AUTO_INCREMENT,
  NOME_DPT VARCHAR(20) NOT NULL,
  FK_ID_FILIAL INT NOT NULL,
  PRIMARY KEY(ID_DPT),
 FOREIGN KEY(FK_ID_FILIAL) REFERENCES FILIAL(ID_FILIAL)
);


CREATE TABLE FUNCIONARIO(
  ID_FUNCIONARIO INT NOT NULL AUTO_INCREMENT,
  LOGIN VARCHAR(20) NOT NULL,
  SENHA VARCHAR(100) NOT NULL,
  CPF VARCHAR(14) UNIQUE NOT NULL,
  NOME_FUNC VARCHAR(50) NOT NULL,
  CARGO VARCHAR(30) NOT NULL,
  FK_ID_DPT INT NOT NULL,
  FK_ID_FILIAL INT NOT NULL,
  PRIMARY KEY(ID_FUNCIONARIO),
  FOREIGN KEY(FK_ID_DPT) REFERENCES DEPARTAMENTO(ID_DPT),
  FOREIGN KEY(FK_ID_FILIAL) REFERENCES FILIAL(ID_FILIAL)
);

CREATE TABLE PRODUTO(
  ID_PRODUTO INT NOT NULL AUTO_INCREMENT,
  NOME_PRODUTO VARCHAR(150) NOT NULL,
  VALOR_UNIT NUMERIC(10,2) NOT NULL,
  IDIOMA VARCHAR(20),
  CATEGORIA VARCHAR(20),
  QTD INT NOT NULL,
  AUTOR VARCHAR(50),
  ISBN VARCHAR(50),
  PAGINAS INT,
  EDITORA VARCHAR(50),
  TEMPO VARCHAR(15),
  FK_ID_FILIAL INT NOT NULL,
  PRIMARY KEY(ID_PRODUTO),
  FOREIGN KEY(FK_ID_FILIAL) REFERENCES FILIAL(ID_FILIAL)
);


CREATE TABLE PEDIDOVENDA(
  ID_VENDA INT NOT NULL AUTO_INCREMENT,
  DATA DATE NOT NULL,
  VALOR_TOTAL NUMERIC(10,2) NOT NULL,
  FK_ID_CLIENTE INT,
  PRIMARY KEY(ID_VENDA),
  FOREIGN KEY(FK_ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);


CREATE TABLE ITEMPEDIDO(
  ID_ITEM INT NOT NULL AUTO_INCREMENT,
  QTD INT NOT NULL,
  VALOR_ITEM NUMERIC(10,2) NOT NULL,
  FK_ID_PROD INT NOT NULL,
  FK_ID_VENDA INT ,
  PRIMARY KEY(ID_ITEM),
  FOREIGN KEY(FK_ID_PROD) REFERENCES PRODUTO(ID_PRODUTO),
  FOREIGN KEY(FK_ID_VENDA) REFERENCES PEDIDOVENDA(ID_VENDA)
);



