CREATE DATABASE LIVRARIA;
USE LIVRARIA;

CREATE TABLE CLIENTE (
    ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(50) UNIQUE NOT NULL,
    DATA_NASC Varchar(89),
    SEXO VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(14) NOT NULL,
    PRIMARY KEY(ID_CLIENTE)
);

CREATE TABLE FILIAL(
  ID_FILIAL INT NOT NULL AUTO_INCREMENT,
  NOME_FILIAL VARCHAR(20) NOT NULL,
  CIDADE VARCHAR(25) NOT NULL,
  PRIMARY KEY(ID_FILIAL)
);

CREATE TABLE DEPARTAMENTO(
  ID_DPT INT NOT NULL AUTO_INCREMENT,
  NOME_DPT VARCHAR(20) NOT NULL,  
  PRIMARY KEY(ID_DPT)  
);

CREATE TABLE FUNCIONARIO(
  ID_FUNCIONARIO INT NOT NULL AUTO_INCREMENT,
  LOGIN VARCHAR(20) NOT NULL,
  SENHA VARCHAR(100) NOT NULL,
  CPF VARCHAR(14) UNIQUE NOT NULL,
  NOME_FUNC VARCHAR(50) NOT NULL,
  CARGO VARCHAR(30) NOT NULL,
  FK_ID_DPT INT NOT NULL,
  FK_ID_FILIAL INT NOT NULL,
  PRIMARY KEY(ID_FUNCIONARIO),
  FOREIGN KEY(FK_ID_DPT) REFERENCES DEPARTAMENTO(ID_DPT),
  FOREIGN KEY(FK_ID_FILIAL) REFERENCES FILIAL(ID_FILIAL)
);

CREATE TABLE PRODUTO(
  ID_PRODUTO INT NOT NULL AUTO_INCREMENT,
  NOME_PRODUTO VARCHAR(150) NOT NULL,
  VALOR_UNIT NUMERIC(10,2) NOT NULL,
  IDIOMA VARCHAR(20),
  CATEGORIA VARCHAR(20),
  QTD INT NOT NULL,
  AUTOR VARCHAR(50),
  ISBN VARCHAR(50),
  PAGINAS INT,
  EDITORA VARCHAR(50),
  TEMPO VARCHAR(15),
  FK_ID_FILIAL INT NOT NULL,
  PRIMARY KEY(ID_PRODUTO),
  FOREIGN KEY(FK_ID_FILIAL) REFERENCES FILIAL(ID_FILIAL)
);


CREATE TABLE PEDIDOVENDA(
  ID_VENDA INT NOT NULL AUTO_INCREMENT,
  DATA DATE NOT NULL,
  VALOR_TOTAL NUMERIC(10,2) NOT NULL,
  FK_ID_CLIENTE INT,
  FK_ID_FILIAL INT,
  PRIMARY KEY(ID_VENDA),
  FOREIGN KEY(FK_ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
  FOREIGN KEY(FK_ID_FILIAL) REFERENCES FILIAL(ID_FILIAL)
);


CREATE TABLE ITEMPEDIDO(
  ID_ITEM INT NOT NULL AUTO_INCREMENT,
  QTD INT NOT NULL,
  VALOR_ITEM NUMERIC(10,2) NOT NULL,
  FK_ID_PROD INT NOT NULL,
  FK_ID_VENDA INT ,
  PRIMARY KEY(ID_ITEM),
  FOREIGN KEY(FK_ID_PROD) REFERENCES PRODUTO(ID_PRODUTO),
  FOREIGN KEY(FK_ID_VENDA) REFERENCES PEDIDOVENDA(ID_VENDA)
);

CREATE TABLE DPT_FILIAL(
  ID INT NOT NULL AUTO_INCREMENT,
  FK_ID_DPT INT,
  FK_ID_FILIAL INT,
  PRIMARY KEY(ID),
  FOREIGN KEY(FK_ID_DPT) REFERENCES DEPARTAMENTO(ID_DPT),
  FOREIGN KEY(FK_ID_FILIAL) REFERENCES FILIAL(ID_FILIAL)
);

INSERT INTO LIVRARIA.FILIAL(NOME_FILIAL, CIDADE)
VALUES ('Matriz', 'São Paulo');
INSERT INTO LIVRARIA.FILIAL(NOME_FILIAL, CIDADE)
VALUES ('Brasilia','Brasilia');
INSERT INTO LIVRARIA.FILIAL(NOME_FILIAL, CIDADE)
VALUES ('Campina Grande','Campina Grande');
INSERT INTO LIVRARIA.FILIAL(NOME_FILIAL, CIDADE)
VALUES ('Joinville','Joinville');

/*INSERT PARA DEPARTAMENTO PARA FILIAL MATRIZ - 1*/
INSERT INTO LIVRARIA.DEPARTAMENTO(NOME_DPT)
VALUES('DIRETORIA');
INSERT INTO LIVRARIA.DEPARTAMENTO(NOME_DPT)
VALUES('PRODUTOS/MARKETING');
INSERT INTO LIVRARIA.DEPARTAMENTO(NOME_DPT)
VALUES('TI');
INSERT INTO LIVRARIA.DEPARTAMENTO(NOME_DPT)
VALUES('VENDAS');


INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(1,1);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(2,1);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(3,1);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(4,1);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(1,2);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(2,2);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(3,2);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(4,2);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(1,3);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(2,3);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(3,3);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(4,3);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(1,4);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(2,4);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(3,4);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(4,4);


INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES('admin','$2a$10$RYBjpMPbvdcVMICq8BtiB.Q0yMy.ObnLD4znEVbb9HGVwl9Vq.cIu','1','admin','Analista','3','1');


SELECT * FROM FILIAL;

