CREATE DATABASE LIVRARIA;
USE LIVRARIA;

CREATE TABLE CLIENTE (
    ID_CLIENTE INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(50) UNIQUE NOT NULL,
    DATA_NASC DATE NOT NULL,
    SEXO VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(14) NOT NULL,
    PRIMARY KEY(ID_CLIENTE)
);

CREATE TABLE FILIAL(
  ID_FILIAL INT NOT NULL AUTO_INCREMENT,
  NOME_FILIAL VARCHAR(20) NOT NULL,
  CIDADE VARCHAR(25) NOT NULL,
  PRIMARY KEY(ID_FILIAL)
);

CREATE TABLE DEPARTAMENTO(
  ID_DPT INT NOT NULL AUTO_INCREMENT,
  NOME_DPT VARCHAR(20) NOT NULL,  
  PRIMARY KEY(ID_DPT)  
);

CREATE TABLE FUNCIONARIO(
  ID_FUNCIONARIO INT NOT NULL AUTO_INCREMENT,
  LOGIN VARCHAR(20) NOT NULL,
  SENHA VARCHAR(100) NOT NULL,
  CPF VARCHAR(14) UNIQUE NOT NULL,
  NOME_FUNC VARCHAR(50) NOT NULL,
  CARGO VARCHAR(30) NOT NULL,
  FK_ID_DPT INT NOT NULL,
  FK_ID_FILIAL INT NOT NULL,
  PRIMARY KEY(ID_FUNCIONARIO),
  FOREIGN KEY(FK_ID_DPT) REFERENCES DEPARTAMENTO(ID_DPT),
  FOREIGN KEY(FK_ID_FILIAL) REFERENCES FILIAL(ID_FILIAL)
);

CREATE TABLE PRODUTO(
  ID_PRODUTO INT NOT NULL AUTO_INCREMENT,
  NOME_PRODUTO VARCHAR(150) NOT NULL,
  VALOR_UNIT NUMERIC(10,2) NOT NULL,
  IDIOMA VARCHAR(20),
  CATEGORIA VARCHAR(20),
  QTD INT NOT NULL,
  AUTOR VARCHAR(50),
  ISBN VARCHAR(50),
  PAGINAS INT,
  EDITORA VARCHAR(50),
  TEMPO VARCHAR(15),
  FK_ID_FILIAL INT NOT NULL,
  PRIMARY KEY(ID_PRODUTO),
  FOREIGN KEY(FK_ID_FILIAL) REFERENCES FILIAL(ID_FILIAL)
);

CREATE TABLE PEDIDOVENDA(
  ID_VENDA INT NOT NULL AUTO_INCREMENT,
  DATA DATE NOT NULL,
  VALOR_TOTAL NUMERIC(10,2) NOT NULL,
  FK_ID_CLIENTE INT,
  FK_ID_FILIAL INT,
  PRIMARY KEY(ID_VENDA),
  FOREIGN KEY(FK_ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
  FOREIGN KEY(FK_ID_FILIAL) REFERENCES FILIAL(ID_FILIAL)
);

CREATE TABLE ITEMPEDIDO(
  ID_ITEM INT NOT NULL AUTO_INCREMENT,
  QTD INT NOT NULL,
  VALOR_ITEM NUMERIC(10,2) NOT NULL,
  FK_ID_PROD INT NOT NULL,
  FK_ID_VENDA INT ,
  PRIMARY KEY(ID_ITEM),
  FOREIGN KEY(FK_ID_PROD) REFERENCES PRODUTO(ID_PRODUTO),
  FOREIGN KEY(FK_ID_VENDA) REFERENCES PEDIDOVENDA(ID_VENDA)
);

CREATE TABLE DPT_FILIAL(
  ID INT NOT NULL AUTO_INCREMENT,
  FK_ID_DPT INT,
  FK_ID_FILIAL INT,
  PRIMARY KEY(ID),
  FOREIGN KEY(FK_ID_DPT) REFERENCES DEPARTAMENTO(ID_DPT),
  FOREIGN KEY(FK_ID_FILIAL) REFERENCES FILIAL(ID_FILIAL)
);

INSERT INTO LIVRARIA.FILIAL(NOME_FILIAL, CIDADE)
VALUES ('Matriz', 'São Paulo');
INSERT INTO LIVRARIA.FILIAL(NOME_FILIAL, CIDADE)
VALUES ('Brasilia','Brasilia');
INSERT INTO LIVRARIA.FILIAL(NOME_FILIAL, CIDADE)
VALUES ('Campina Grande','Campina Grande');
INSERT INTO LIVRARIA.FILIAL(NOME_FILIAL, CIDADE)
VALUES ('Joinville','Joinville');

/*INSERT PARA DEPARTAMENTO PARA FILIAL MATRIZ - 1*/
INSERT INTO LIVRARIA.DEPARTAMENTO(NOME_DPT)
VALUES('DIRETORIA');
INSERT INTO LIVRARIA.DEPARTAMENTO(NOME_DPT)
VALUES('PRODUTOS/MARKETING');
INSERT INTO LIVRARIA.DEPARTAMENTO(NOME_DPT)
VALUES('TI');
INSERT INTO LIVRARIA.DEPARTAMENTO(NOME_DPT)
VALUES('VENDAS');

INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(1,1);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(2,1);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(3,1);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(4,1);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(1,2);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(2,2);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(3,2);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(4,2);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(1,3);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(2,3);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(3,3);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(4,3);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(1,4);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(2,4);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(3,4);
INSERT INTO DPT_FILIAL (FK_ID_DPT,FK_ID_FILIAL)VALUES(4,4);

/*INSERT PARA FUNCIONÁRIOS INICIAIS*/
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES('gabriel.matriz','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','1','Gabriel Vital','Analista','3','1');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES('beatriz.matriz','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','2','Beatriz Silva','Diretor','1','1');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES('pedro.matriz','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','3','Pedro Almeida','Vendedor','4','1');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES ('micael.matriz','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','17','Micael Santos','Gerente','4','1');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES ('everton.matriz','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','21','Everton Coutinho','Gerente_Global','4','1');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES('diego.matriz','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','4','Diego Mansoldo','Backoffice','2','1');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES('gabriel.brasilia','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','5','Gabriel Vital','Analista','3','2');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES('beatriz.brasilia','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','6','Beatriz Silva','Diretor','1','2');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES('pedro.brasilia','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','7','Pedro Almeida','Vendedor','4','2');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES ('micael.brasilia','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','18','Micael Santos','Gerente','4','2');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES ('everton.brasilia','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','22','Everton Coutinho','Gerente_Global','4','2');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES('diego.brasilia','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','8','Diego Mansoldo','Backoffice','2','2');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES('gabriel.campina','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','9','Gabriel Vital','Analista','3','3');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES('beatriz.campina','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','10','Beatriz Silva','Diretor','1','3');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES('pedro.campina','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','11','Pedro Almeida','Vendedor','4','3');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES('diego.campina','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','12','Diego Mansoldo','Backoffice','2','3');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES ('micael.campina','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','19','Micael Santos','Gerente','4','3');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES ('everton.campina','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','23','Everton Coutinho','Gerente_Global','4','3');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES('gabriel.joinville','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','13','Gabriel Vital','Analista','3','4');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES('beatriz.joinville','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','14','Beatriz Silva','Diretor','1','4');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES('pedro.joinville','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','15','Pedro Almeida','Vendedor','4','4');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES('diego.joinville','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','16','Diego Mansoldo','Backoffice','2','4');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES ('micael.joinville','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','20','Micael Santos','Gerente','4','4');
INSERT INTO LIVRARIA.FUNCIONARIO(LOGIN,SENHA,CPF,NOME_FUNC,CARGO,FK_ID_DPT,FK_ID_FILIAL) VALUES ('everton.joinville','$2a$10$kuVb1DMvjrZ3HaBeAaKYeOvSs.4ilmGgW69t8I05ldL5y5eq3MHT.','24','Everton Coutinho','Gerente_Global','4','4');

/*INSERT PARA PRODUTOS INICIAIS*/
INSERT INTO LIVRARIA.PRODUTO (NOME_PRODUTO, VALOR_UNIT, IDIOMA, CATEGORIA, QTD, AUTOR, ISBN, PAGINAS, EDITORA, TEMPO, FK_ID_FILIAL) VALUES ('Harry Potter', 15, 'Português', 'Livro', 10, 'J. K. Rowling', '978-0-60-503907-0', 432, 'Rocco',null, 1);
INSERT INTO LIVRARIA.PRODUTO (NOME_PRODUTO, VALOR_UNIT, IDIOMA, CATEGORIA, QTD, AUTOR, ISBN, PAGINAS, EDITORA, TEMPO, FK_ID_FILIAL) VALUES ('Batman', 35, 'Português', 'HQ / Mangá', 20, 'Bill Finger', null, 250, 'DC Comics',null, 1);
INSERT INTO LIVRARIA.PRODUTO (NOME_PRODUTO, VALOR_UNIT, IDIOMA, CATEGORIA, QTD, AUTOR, ISBN, PAGINAS, EDITORA, TEMPO, FK_ID_FILIAL) VALUES ('Metallica', 50, 'Inglês', 'CD / DVD', 10, null, null, null, null, '120', 1);
INSERT INTO LIVRARIA.PRODUTO (NOME_PRODUTO, VALOR_UNIT, IDIOMA, CATEGORIA, QTD, AUTOR, ISBN, PAGINAS, EDITORA, TEMPO, FK_ID_FILIAL) VALUES ('Jogos Vorazes', 120, 'Português', 'Livro', 80, 'Suzanne Collins','264-2-80-123654-2', 250, 'Rocco', null, 2);
INSERT INTO LIVRARIA.PRODUTO (NOME_PRODUTO, VALOR_UNIT, IDIOMA, CATEGORIA, QTD, AUTOR, ISBN, PAGINAS, EDITORA, TEMPO, FK_ID_FILIAL) VALUES ('Homem-Aranha', 45, 'Espanhol', 'HQ / Mangá', 200, 'Stan Lee', null, 600, 'Marvel', null, 2);
INSERT INTO LIVRARIA.PRODUTO (NOME_PRODUTO, VALOR_UNIT, IDIOMA, CATEGORIA, QTD, AUTOR, ISBN, PAGINAS, EDITORA, TEMPO, FK_ID_FILIAL) VALUES ('Aerosmith', 50, 'Inglês', 'CD / DVD', 100, null, null, null, null, '60', 2);
INSERT INTO LIVRARIA.PRODUTO (NOME_PRODUTO, VALOR_UNIT, IDIOMA, CATEGORIA, QTD, AUTOR, ISBN, PAGINAS, EDITORA, TEMPO, FK_ID_FILIAL) VALUES ('Como eu Era Antes de Você', 70, 'Inglês', 'Livro', 35, 'Jojo Moyes', '456-1-70-895546-1', 500, 'Penguin Books', null, 2);
INSERT INTO LIVRARIA.PRODUTO (NOME_PRODUTO, VALOR_UNIT, IDIOMA, CATEGORIA, QTD, AUTOR, ISBN, PAGINAS, EDITORA, TEMPO, FK_ID_FILIAL) VALUES ('One Piece 91', 50, 'Japonês', 'HQ / Mangá', 320, 'Eiichiro Oda', null, 750, 'Shueisha', null, 2);
INSERT INTO LIVRARIA.PRODUTO (NOME_PRODUTO, VALOR_UNIT, IDIOMA, CATEGORIA, QTD, AUTOR, ISBN, PAGINAS, EDITORA, TEMPO, FK_ID_FILIAL) VALUES ('Pearl Jam', 35, 'Inglês', 'CD / DVD', 120, null, null, null, null, '180', 3);
INSERT INTO LIVRARIA.PRODUTO (NOME_PRODUTO, VALOR_UNIT, IDIOMA, CATEGORIA, QTD, AUTOR, ISBN, PAGINAS, EDITORA, TEMPO, FK_ID_FILIAL) VALUES ('Ansiedade', 30, 'Português', 'Livro', 80, 'Augusto Cury','346-3-90-654521-3', 300, 'Saraiva', null, 4);
INSERT INTO LIVRARIA.PRODUTO (NOME_PRODUTO, VALOR_UNIT, IDIOMA, CATEGORIA, QTD, AUTOR, ISBN, PAGINAS, EDITORA, TEMPO, FK_ID_FILIAL) VALUES ('Homem-Formiga', 45, 'Inglês', 'HQ / Mangá', 250, 'Stan Lee', null, 620, 'Marvel', null, 4);
INSERT INTO LIVRARIA.PRODUTO (NOME_PRODUTO, VALOR_UNIT, IDIOMA, CATEGORIA, QTD, AUTOR, ISBN, PAGINAS, EDITORA, TEMPO, FK_ID_FILIAL) VALUES ('U2', 60, 'Inglês', 'CD / DVD', 100, null, null, null, null, '260', 4);

/*INSERT PARA CLIENTES INICIAIS*/
INSERT INTO LIVRARIA.CLIENTE (NOME, CPF, DATA_NASC, SEXO, EMAIL, TELEFONE) VALUES ('Claudia da Silva', '051.485.568-11', '1983-01-26', 'Feminino', 'claudia.silva@email.com', '(11)98746-3542');
INSERT INTO LIVRARIA.CLIENTE (NOME, CPF, DATA_NASC, SEXO, EMAIL, TELEFONE) VALUES ('Antonio Pereira', '123.456.845-25', '1989-06-13', 'Masculino', 'antonio.s@email.com', '(11)95487-5657');
INSERT INTO LIVRARIA.CLIENTE (NOME, CPF, DATA_NASC, SEXO, EMAIL, TELEFONE) VALUES ('Elisa Analu', '459.348.554-36', '1994-04-17', 'Masculino', 'eaidac@email.com', '(11)94575-1597');